server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MICROSERVICES
    username: root
    password: cna583RW
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: update
      boot:
        allow_jdbc_metadata_access: false
    show-sql: true
