name: Integration Artifactory

on:
    push: 
        branches:
            - "main"

env:
  JF_URL: ${{ vars.JF_URL }}
  JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
  
jobs:
    add_integration:
        runs-on: [ ubuntu-latest ]
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '22'
                  distribution: 'temurin'
            - name: Install dependencies Maven
              run: mvn install -DskipTests -s ./settings.xml
            - name: Test
              run: |
                  ls
                  pwd
            # - name: Build with Maven
              # run: mvn clean package -DskipTests
            - uses: jfrog/setup-jfrog-cli@v4
            - name: Login to artifactory
              run: jf c add --access-token "$JF_ACCESS_TOKEN"
            - name: Ping to artifactory
              run: jf rt ping --url $JF_URL/artifactory
            - name: Upload text
              run: |
                echo "Prueba" > text.txt
                ls -la
                jf rt u text.txt texts




    

  