name: Integration Artifactory

on:
    push: 
        branches:
            - "main"

jobs:
    add_integration:
        runs-on: [ ubuntu-latest ]
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '22'
                  distribution: 'temurin'
            - name: Build with Maven
              run: mvn clean package -DskipTests
            - name: Tests
              run: |
                cd ./target
                ls
            - uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ vars.JF_URL }}
                JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
            - name: Login to artifactory
              run: jf c add --access-token "${{ secrets.JF_ACCESS_TOKEN }}"
            - name: Ping to artifactory
              run: jf rt ping --url ${{ vars.JF_URL }}/artifactory
            - name: Upload the .jar
              run: |
                cd ./target
                jf rt u ducco-0.0.1-SNAPSHOT.jar test
# --access-token $JF_ACCESS_TOKEN






    

  