name: Integration Artifactory

on:
    push: 
        branches:
            - "main"

jobs:
    add_integration:
        runs-on: [ ubuntu-latest ]
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '22'
                  distribution: 'temurin'
            - name: Build with Maven
              run: mvn clean package -DskipTests
            - name: Test
              run: |
                cd ./target
                ls
            - uses: jfrog/setup-jfrog-cli@v4
            - run: jf --version


    

  